name: Deploy React App
on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  vulnerability-assessment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          image-ref: 'ubuntu:14.04'
          format: 'json'
          output: 'trivy-results.json'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
          ignore-unfixed: false
          hide-progress: false
      - name: Create findings to DefectDojo
        if: always()
        run: |
          if [ -s trivy-results.json ]; then
            curl -v -X POST "https://demo.defectdojo.org/api/v2/import-scan/" \
            -H "Authorization: Token 6709ec1a311f350ff8d46f53158228f4ac2b567d" \
            -F "active=true" \
            -F "verified=false" \
            -F "scan_type=Trivy Scan" \
            -F "product=5" \
            -F "engagement=19" \
            -F "file=@trivy-results.json"
            exit 1
          else
            echo "No vulnerabilities were identified"
          fi
  secret-scanning:
    needs: vulnerability-assessment
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Run TruffleHog
      id: trufflehog
      uses: trufflesecurity/trufflehog@main
      continue-on-error: true
      with:
        path: ./
        base: ""
        head: ${{ github.ref_name }}
        extra_args: --results=verified,unverified,unknown --json
    - name: Create finding in DefectDojo
      if: steps.trufflehog.outcome == 'failure'
      run: |
        curl -X POST "https://demo.defectdojo.org/api/v2/findings/" \
        -H "Authorization: Token 6709ec1a311f350ff8d46f53158228f4ac2b567d" \
        -H "Content-Type: application/json" \
        -d '{
          "title": "Secrets identified in ${{ github.event.repository.name }}",
          "description": "TruffleHog detected potential secrets in the latest push to the ${{ github.ref_name }} branch. Manual review is required immediately.",
          "severity": "Critical",
          "active": true,
          "verified": false,
          "numerical_severity": "S0",
          "product": 5, 
          "test": 36,
          "found_by": [133]
        }'
        exit 1
  build-and-deploy:
    needs: secret-scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
  

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
