name: Deploy React App
on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  secret-scanning:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Run TruffleHog
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: ""
        head: ${{ github.ref_name }}
        extra_args: --results=verified,unverified,unknown --json
    - name: Capture Results to File
      if: always()
      # This step takes the logs from the previous step and saves them
      run: |
        gh run view ${{ github.run_id }} --log-step "Run TruffleHog" > trufflehog_results.json
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload to DefectDojo (Demo)
      if: always()
      run: |
        curl -X POST "https://demo.defectdojo.org" \
        -H "Authorization: Token 548afd6fab3bea9794a41b31da0e9404f733e222" \
        -F "active=true" \
        -F "verified=false" \
        -F "scan_type=Trufflehog Scan" \
        -F "product_name=cicdpoc" \
        -F "engagement_name=Security Scan Demo" \
        -F "file=@trufflehog_results.json"
  build-and-deploy:
    needs: secret-scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
  

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
